const auth = require('../auth')
const express = require('express')
const Top5ListController = require('../controllers/top5list-controller')
const UserController = require('../controllers/user-controller')
const LibraryController=require('../controllers/library-controller')
const userModel = require('../models/user-model')
const libraryModel = require('../models/library-model')
const router = express.Router()

router.post('/top5list', auth.verify, Top5ListController.createTop5List)
router.put('/top5list/:id', auth.verify, Top5ListController.updateTop5List)
router.delete('/top5list/:id', auth.verify, Top5ListController.deleteTop5List)
router.get('/top5list/:id', Top5ListController.getTop5ListById)
router.get('/top5lists', Top5ListController.getTop5Lists)
router.get('/top5listpairs', Top5ListController.getTop5ListPairs)

router.post('/register', UserController.registerUser)
router.post('/login',UserController.loginUser)
router.get('/logout',UserController.logoutUser)
router.get('/loggedIn', UserController.getLoggedIn)
router.get('/getUserData',UserController.getUserData)
router.get('/updateUser',UserController.updateUser)

router.post('/library', auth.verify, LibraryController.createLibrary)
router.put('/library/:id', auth.verify, LibraryController.updateLibrary)
router.delete('/library/:id', auth.verify, LibraryController.deleteLibrary)
router.get('/library/:id', auth.verify, LibraryController.getLibraryById)
router.get('/library', auth.verify,LibraryController.getAllLibrary)
router.get('/library/:name', auth.verify,LibraryController.getLibrariesByName)

router.post('/sendEmail', UserController.sendEmail)
router.post('/resetPassword/:userId/:token', auth.verify, auth.verify, UserController.resetPassword)
module.exports = router